name: Test, Upload artifact

on: workflow_dispatch

jobs:
  release:
    runs-on: ubuntu-latest
    name: Build, package and
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build and package project
        run: |
          ls
          cd ProcessProductDetails
          ls
          mvn clean package
